BEGIN;
CREATE TABLE source_records (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source_id text NOT NULL, source_record_id text NOT NULL, retrieved_at timestamptz NOT NULL, observed_at timestamptz, effective_at timestamptz, verification_status text NOT NULL, legal_authority boolean NOT NULL DEFAULT false, payload_hash text, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, UNIQUE(source_id,source_record_id,retrieved_at));
CREATE TABLE geometry_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source_record_uuid uuid NOT NULL REFERENCES source_records(id), geom geometry(Geometry,4326) NOT NULL, valid_from timestamptz, valid_to timestamptz, geometry_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CHECK(ST_IsValid(geom)), CHECK(valid_to IS NULL OR valid_from IS NULL OR valid_to>=valid_from));
CREATE INDEX geometry_versions_geom_gist ON geometry_versions USING gist(geom);
CREATE TABLE interest_claims (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), public_id text NOT NULL UNIQUE, geom geometry(Polygon,4326) NOT NULL, status text NOT NULL DEFAULT 'DRAFT', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK(ST_IsValid(geom)), CHECK(status IN ('DRAFT','SUBMITTED','VERIFYING','CONFLICT','PENDING_AUTHORITY','ELIGIBLE_FOR_PROCEDURE','WITHDRAWN','EXPIRED','CLOSED')));
CREATE INDEX interest_claims_geom_gist ON interest_claims USING gist(geom);
CREATE TABLE claim_assessments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), claim_id uuid NOT NULL REFERENCES interest_claims(id), status text NOT NULL, reason_codes text[] NOT NULL DEFAULT '{}', confidence numeric(5,4), calculated_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz, CHECK(status IN ('UNKNOWN','INSUFFICIENT_DATA','KNOWN_CONFLICT','RESTRICTED','UNDER_REVIEW','POTENTIALLY_ELIGIBLE','ELIGIBLE_FOR_PROCEDURE','OFFICIALLY_CONFIRMED')), CHECK(confidence IS NULL OR (confidence>=0 AND confidence<=1)), CHECK(expires_at IS NULL OR expires_at>=calculated_at));
CREATE TABLE assessment_evidence (assessment_id uuid NOT NULL REFERENCES claim_assessments(id) ON DELETE CASCADE, source_record_uuid uuid NOT NULL REFERENCES source_records(id), PRIMARY KEY(assessment_id,source_record_uuid));
COMMIT;
